# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches:
      - master

env:
  SPRING_PROFILES_ACTIVE: ci
  CODECOV_TOKEN: a61e53cf-e837-4d8a-9e8b-f20d40f03eda

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout
      uses: actions/checkout@v2.1.0

    - name: Setup Java JDK 11
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11

    - name: Restore Build Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.m2/repository
        key: v2-fridge-${{ hashFiles('pom.xml') }}

    - name: Migrate Database With Flyway
      run: mvn -Dflyway.configFiles=configuration/db/${SPRING_PROFILES_ACTIVE}.properties flyway:clean flyway:migrate

    - name: Full Test With Maven
      run: mvn clean -Dskip.surefire.tests=false -D=skip.failsafe.tests=false verify
    
    - name: Codecov Report
      run: curl -s https://codecov.io/bash | bash

    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.0.4
      with:
        heroku_api_key: ${{secrets.HEROKU_TOKEN}}
        heroku_app_name: fridge-development
        heroku_email: ryujinwrath@gmail.com
        docker_heroku_process_type: web
